loki:
  address: http://10.125.9.37:3100
  query:
    system: gmu
    env: env
    application: backend-app
# Максимум 5000, loki не позволяет вытащить больше
    batchSize: 100
    from: '2025-04-04 11:00:00'
    end: '2025-03-14 21:00:00'