loki:
  address: http://10.125.9.37:3100
  query:
    system: passport-rf
    env: uat
    application: passport-rf-external-backend
# Максимум 5000, loki не позволяет вытащить больше
    batchSize: 1000
    from: '2025-07-21 11:47:25'
    end: '2025-07-21 11:47:35'