[versions]
spring-boot = "2.7.8"
spring-cloud = "2021.0.9"
mapstruct = "1.6.2"
lombok = "1.18.30"
cloud-dependecy = "1.1.4"
asciidoctor = "4.0.5"
kotlin = "2.0.20"
ben-manes = "0.45.0"

[libraries]
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-cloud-starter-openfeign = { module = "org.springframework.cloud:spring-cloud-starter-openfeign" }
jakarta-validation-api = { module = "jakarta.validation:jakarta.validation-api" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind" }
spring-cloud-starter-loadbalancer = { module = "org.springframework.cloud:spring-cloud-starter-loadbalancer" }
mockito-core = { module = "org.mockito:mockito-core" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }

[plugins]
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "cloud-dependecy" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
asciidoctor = { id = "org.asciidoctor.jvm.convert", version.ref = "asciidoctor" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
ben-manes-versions = { id = "com.github.ben-manes.versions", version.ref = "ben-manes" }